# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 283)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(90, 30, 381, 41))
        self.title.setTextFormat(QtCore.Qt.PlainText)
        self.title.setObjectName("title")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title.setFont(font)

        self.label_admin = QtWidgets.QLabel(self.centralwidget)
        self.label_admin.setGeometry(QtCore.QRect(190, 100, 61, 21))
        self.label_admin.setObjectName("label_admin")
        self.label_passwd = QtWidgets.QLabel(self.centralwidget)
        self.label_passwd.setGeometry(QtCore.QRect(190, 140, 61, 21))
        self.label_passwd.setObjectName("label_passwd")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(260, 100, 141, 21))
        self.username.setObjectName("username")
        self.passwd = QtWidgets.QLineEdit(self.centralwidget)
        self.passwd.setGeometry(QtCore.QRect(260, 140, 141, 21))
        self.passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd.setObjectName("passwd")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 100, 61, 61))
        self.label.setStyleSheet("border-image: url(:/NingxiaUniversityLogo/ningxiaUniversity.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于图神经网络的管道图像缺陷分类系统"))
        self.title.setText(_translate("MainWindow", "基于图神经网络的管道图像缺陷分类系统"))
        self.label_admin.setText(_translate("MainWindow", "管理员："))
        self.label_passwd.setText(_translate("MainWindow", "密 码："))
        self.pushButton.setText(_translate("MainWindow", "登录"))

