# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(40, 30, 51, 23))
        self.browseButton.setObjectName("browseButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 70, 41, 16))
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(60, 100, 371, 391))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(540, 100, 371, 391))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.startProgramButton = QtWidgets.QPushButton(self.centralwidget)
        self.startProgramButton.setGeometry(QtCore.QRect(450, 280, 75, 23))
        self.startProgramButton.setObjectName("startProgramButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(50, 510, 81, 23))
        self.removeButton.setObjectName("removeButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(940, 100, 91, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setPlaceholderText("图像增强")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.exitProgram = QtWidgets.QPushButton(self.centralwidget)
        self.exitProgram.setGeometry(QtCore.QRect(860, 20, 81, 41))
        self.exitProgram.setObjectName("exitProgram")
        self.defect_classification = QtWidgets.QPushButton(self.centralwidget)
        self.defect_classification.setGeometry(QtCore.QRect(430, 20, 101, 41))
        self.defect_classification.setObjectName("defect_classification")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于图神经网络的管道图像缺陷分类系统"))
        self.browseButton.setText(_translate("MainWindow", "浏览"))
        self.label.setText(_translate("MainWindow", "输入"))
        self.startProgramButton.setText(_translate("MainWindow", "进入处理→"))
        self.label_2.setText(_translate("MainWindow", "图像增强"))
        self.removeButton.setText(_translate("MainWindow", "移除当前"))
        self.comboBox.setCurrentText(_translate("MainWindow", "图像增强"))
        self.comboBox.setItemText(0, _translate("MainWindow", "灰度化"))
        self.comboBox.setItemText(1, _translate("MainWindow", "亮度抖动"))
        self.comboBox.setItemText(2, _translate("MainWindow", "色彩抖动"))
        self.exitProgram.setText(_translate("MainWindow", "退出系统"))
        self.defect_classification.setText(_translate("MainWindow", "缺陷分类"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action_open.setText(_translate("MainWindow", "打开"))
        self.action_save.setText(_translate("MainWindow", "保存"))
        self.action_exit.setText(_translate("MainWindow", "退出"))
